# Generated by Django 4.2.3 on 2023-07-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSMS',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('phone_num', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('auth_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
