# Generated by Django 4.2.3 on 2023-07-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="user_id",
            new_name="user",
        ),
    ]
