# Generated by Django 4.2.3 on 2023-07-13 15:37

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tag", "0002_rename_user_id_tag_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("finish_at", models.DateTimeField(blank=True, null=True)),
                ("update_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_time", models.FloatField(blank=True, null=True)),
                ("cumulative_time", models.FloatField(blank=True, null=True)),
                ("progress_rate", models.FloatField(blank=True, null=True)),
                ("is_scheduled", models.BooleanField(blank=True, default=False)),
                ("is_completed", models.BooleanField(blank=True, default=False)),
                (
                    "avaliable_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), blank=True, null=True, size=7
                    ),
                ),
                (
                    "exception_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tag.tag"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
