# Generated by Django 4.2.3 on 2023-07-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="finish_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="start_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="update_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
