# Generated by Django 4.2.3 on 2023-07-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goal", "0002_alter_goal_finish_at_alter_goal_start_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="prev_cumulative_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="prev_progress_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="prev_residual_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="prev_update_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="residual_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
