# Generated by Django 4.2.3 on 2023-07-18 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0004_remove_goal_avaliable_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpossibleDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.goal')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goal.goal')),
            ],
        ),
    ]
