# Generated by Django 4.2.3 on 2023-07-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0005_impossibledates_availabledays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impossibledates',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
