# Generated by Django 4.2.3 on 2023-07-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0007_dailyhourofgoals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableDays',
        ),
    ]
