name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: omin-kwon/cheetah-django
          stage: main
          yaml: >
            name: cheetah-django

            app: python@3.9

            options:
              env:
                - name: SECRET_KEY
                  value: django-insecure-hi5i^q17*76sq=%k)ih_mfctc#ql+!7ah5w2tc$f1)rouzsrje
                - name: DJANGO_SUPERUSER_USERNAME
                  value: om0127
                - name: DJANGO_SUPERUSER_PASSWORD
                  value: happy0215*
                - name: DJANGO_SUPERUSER_EMAIL
                  value: om0127@snu.ac.kr
                - name: NCLOUD_ACCESS_KEY
                  value: zECJaXyy1dHSxiGHr98O
                - name: NCLOUD_SECRET_KEY
                  value: TkiyOPOdPcmWjtiqiDbRsrAhZrE4jXveNa56XCgC
                - name: SERVICE_ID
                  value: ncp:sms:kr:311774967554:cheetah
                - name: SEND_PHONE_NUM
                  value: "01082547044"
                - name: subject
                  value: netamijr@gmail.com
                - name: vapidPublic
                  value: BJTOjEEtbYHhIH0t2AUWDFyhQz04JV9Nq6mgtu5-D8FHgdvFwIZTxfU1SaEjEn4SkmPNDkPvlDChOZDhC29P05Y
                - name: vapidPrivate
                  value: uwtJnHtFGv1qEytcCB2E31sO4eQ01LRU0qjL4cqWec4
              ports: 8000
              start: python3 manage.py runserver 0:8000
              prestart: python3 manage.py makemigrations && python3 manage.py migrate &&
                python3 manage.py createsuperuser --noinput --skip-checks
              buildenv:
                - name: subject
                  value: netamijr@gmail.com
                - name: vapidPublic
                  value: BJTOjEEtbYHhIH0t2AUWDFyhQz04JV9Nq6mgtu5-D8FHgdvFwIZTxfU1SaEjEn4SkmPNDkPvlDChOZDhC29P05Y
                - name: vapidPrivate
                  value: uwtJnHtFGv1qEytcCB2E31sO4eQ01LRU0qjL4cqWec4
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
